### ISSUE TITLE
LTC signal always fails after 1:11hr

### ISSUE THREAD

**Issue by jamie-macleod** [mitkunz/diy_timecode_generator#2]
Having an issue where LTC signal will stop after about 1:11hr. 
This happens every time the units get used and it doesn't matter if they are synced or running individually. 

A friend suggested that it is related to the _micros()_ function which "will overflow (go back to zero), after approximately 70 minutes". 
This makes sense why it fails after 1:11hr as I assume it'll be 70min + the 1min initial sync interval. 

Unfortunately I'm not experienced enough to know how to solve the issue, but thought I'd share as sadly the units are pretty much unusable for a long shoot day at the moment.

**Comment by mitkunz** [comment]
Hi Jamie,

Im currently quite busy for work, but will get to your issues as soon as I can. I might have a good idea on how to resolve the rollover issue.

Cheers

**Comment by jamie-macleod** [comment]
Hi Tim,
No worries - work has to take priority!

I'll update if I find anything on my end.

**Comment by AlanWills** [comment]
Hey Tim,

I'm the friend Jamie mentioned - I did a bit of debugging into this and tried to solve it naively, but was unsuccessful.  Some thoughts and info you may find useful:

- As Jamie said, _**micros**_ seems to be the problem; is there a way to convert the code to use **_millis_** instead?  That would dramatically increase the lifespan before we get rollover.  I gave that a go myself, but I couldn't get it working (possibly related to the bit timer, it's hard to debug without being able to run on a device)

- I was also wondering if it was data type related, I tried changing everything time related to an unsigned long long, but that didn't fix the issue either

Hope this helps a little

**Comment by mitkunz** [comment]
i am currently not able to test, because of covid. I can't get to the devices which are at work unfortunately. 

but I implemented the changes to the datatypes for all related variables and also added a check for rollover in the getAdjustedMicros() function. theoretically this should resolve the issue, because now the maximum value for adjustedMicros should be 18446744073709551615 microseconds which would be around 213503982 days. that should be enough. Feel free to check the code on device to confirm.
unsigned long long is 64bit compared to unsigned long (32bit), which was used by accident in some cases.

i also deleted some unused variables in the define segment.

**Comment by mitkunz** [comment]
I've tested the code on my end and it seems to be working (at least after over 24h), so I will close this issue for now as solved.
